In [42]:
from __future__ import print_function
import matplotlib
import matplotlib.pyplot as plt
import tensorflow as tf
import time

def get_times(maximum_time, steps):
    i = 0
    device_times = {
        "/gpu:0":[],
        "/cpu:0":[]
    }
    device1 = "/gpu:0"
    device2 = "/cpu:0"
    matrix_sizes = range(500,50000,50)
    for size in matrix_sizes:
        for device_name in device_times.keys():

            print("####### Calculating on the " + device_name + " #######")

            shape = (size,size)
            data_type = tf.float16
            with tf.device(device_name):
                r1 = tf.random.uniform(shape=shape, minval=0, maxval=1, dtype=data_type)
                r2 = tf.random.uniform(shape=shape, minval=0, maxval=1, dtype=data_type)
                dot_operation = tf.matmul(r2, r1)


            # with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as session:
                start_time = time.time()
                print(tf.matmul(r2, r1))
                # result = session.run(dot_operation)
                time_taken = time.time() - start_time
                # print(result)
                device_times[device_name].append(time_taken)

            print(device_times, steps)

            if time_taken > maximum_time:
                return device_times, matrix_sizes
            
            if i > steps:
                print(device_times, matrix_sizes)
                return device_times, matrix_sizes
            i += 1
            
 


device_times, matrix_sizes = get_times(1.5, 100)
gpu_times = device_times["/gpu:0"]
cpu_times = device_times["/cpu:0"]

plt.plot(matrix_sizes[:len(gpu_times)], gpu_times, 'o-')
plt.plot(matrix_sizes[:len(cpu_times)], cpu_times, 'o-')
print(gpu_times)
print(cpu_times)
plt.ylabel('Time')
plt.xlabel('Matrix size')
plt.show()

####### Calculating on the /gpu:0 #######
tf.Tensor(
[[123.44 124.56 130.5  ... 128.4  132.9  121.75]
 [122.06 118.06 124.06 ... 118.06 128.8  122.5 ]
 [121.8  120.2  122.4  ... 120.8  125.75 118.94]
 ...
 [123.44 119.1  126.   ... 121.1  130.2  121.2 ]
 [126.56 125.4  126.56 ... 123.9  132.6  119.5 ]
 [126.94 119.56 125.94 ... 121.4  130.4  122.94]], shape=(500, 500), dtype=float16)
{'/gpu:0': [0.0010025501251220703], '/cpu:0': []} 100
####### Calculating on the /cpu:0 #######
tf.Tensor(
[[125.9  123.4  121.5  ... 118.5  127.56 124.06]
 [122.75 123.1  115.8  ... 122.5  125.5  127.5 ]
 [124.9  121.4  116.1  ... 120.9  128.   128.2 ]
 ...
 [123.   127.7  122.25 ... 123.75 129.   125.9 ]
 [128.2  125.44 119.   ... 123.4  129.   127.75]
 [128.2  128.6  121.9  ... 124.6  130.5  132.5 ]], shape=(500, 500), dtype=float16)
{'/gpu:0': [0.0010025501251220703], '/cpu:0': [0.21122050285339355]} 100
####### Calculating on the /gpu:0 #######
tf.Tensor(
[[130.2 133.2 138.9 ... 134.4 143.4 142. ]
 [1

tf.Tensor(
[[210.1 210.  216.5 ... 216.9 215.8 223.2]
 [206.2 209.2 221.8 ... 215.6 212.1 221.8]
 [208.5 212.1 220.6 ... 217.2 211.  226.2]
 ...
 [203.6 203.  209.8 ... 211.2 203.5 215.5]
 [208.8 208.1 220.8 ... 218.5 209.  215.1]
 [206.9 209.  220.5 ... 216.1 212.2 218.8]], shape=(850, 850), dtype=float16)
{'/gpu:0': [0.0010025501251220703, 0.0010037422180175781, 0.0010039806365966797, 0.0015048980712890625, 0.001003265380859375, 0.001505136489868164, 0.0015048980712890625, 0.0015048980712890625], '/cpu:0': [0.21122050285339355, 0.27844905853271484, 0.3677535057067871, 0.47160816192626953, 0.5970354080200195, 0.7169439792633057, 0.867457389831543, 1.030513048171997]} 100
####### Calculating on the /gpu:0 #######
tf.Tensor(
[[224.  218.2 229.9 ... 233.9 228.5 230.1]
 [226.  225.1 233.5 ... 236.1 229.9 229.6]
 [222.8 219.  225.4 ... 229.6 228.4 230.4]
 ...
 [223.  217.1 224.5 ... 229.5 225.8 223.4]
 [218.4 215.6 225.5 ... 225.9 228.6 224. ]
 [221.  213.1 218.4 ... 217.9 216.4 217.6]], s

KeyboardInterrupt: 

In [10]:
from __future__ import print_function
import matplotlib
import matplotlib.pyplot as plt
import tensorflow as tf
import time

def get_times(device, seconds):
    i = 0
    start_time = time.time()
    matrix_sizes = range(100,10000,10)
    
    for size in matrix_sizes:

        # print("####### Calculating on the " + device + " #######")

        shape = (size,size)
        data_type = tf.float16
        with tf.device(device):
            r1 = tf.random.uniform(shape=shape, minval=0, maxval=1, dtype=data_type)
            r2 = tf.random.uniform(shape=shape, minval=0, maxval=1, dtype=data_type)
            print("Calculating...", i)
            dot_operation = tf.matmul(r2, r1)
            # print(result)
            
            print(dot_operation)
            current_time = time.time()
            if current_time > start_time + seconds:
                return i, matrix_sizes

            else:
                i += 1
 
i = 0
device1 = "/gpu:0"
device2 = "/cpu:0"
i1, matrix_sizes1 = get_times(device1, 15)
i2, matrix_sizes2 = get_times(device2, 15)
print("Operations on GPU:", i1)
print("Operations on CPU:", i2)
# print("Matrix:", matrix_sizes)
#plt.plot(matrix_sizes[:len(gpu_times)], gpu_times, 'o-')
#plt.plot(matrix_sizes[:len(cpu_times)], cpu_times, 'o-')
#print(gpu_times)
#print(cpu_times)
#plt.ylabel('Time')
#plt.xlabel('Matrix size')
#plt.show()

Calculating... 0
tf.Tensor(
[[26.14 26.78 25.73 ... 25.08 27.1  23.23]
 [23.25 23.02 24.72 ... 24.81 22.67 22.22]
 [25.12 23.86 23.77 ... 24.67 26.2  23.86]
 ...
 [24.89 25.88 25.67 ... 24.95 25.95 24.12]
 [25.61 27.1  26.83 ... 26.03 26.38 25.02]
 [25.8  24.66 25.08 ... 24.44 24.42 25.14]], shape=(100, 100), dtype=float16)
Calculating... 1
tf.Tensor(
[[29.77 27.84 29.61 ... 22.52 27.64 25.7 ]
 [29.84 29.3  28.66 ... 25.53 26.33 29.08]
 [29.08 30.38 30.5  ... 25.4  29.19 30.11]
 ...
 [28.2  26.97 27.34 ... 22.3  26.47 26.53]
 [33.34 33.25 32.6  ... 27.58 32.1  32.84]
 [30.05 30.36 31.05 ... 24.73 29.47 30.81]], shape=(110, 110), dtype=float16)
Calculating... 2
tf.Tensor(
[[27.1  31.2  32.97 ... 29.44 32.12 30.64]
 [29.8  30.4  31.31 ... 30.19 31.97 28.81]
 [29.98 31.05 33.2  ... 30.81 32.38 30.53]
 ...
 [28.23 31.97 33.8  ... 30.3  33.03 29.28]
 [26.06 27.98 31.1  ... 27.17 27.72 27.31]
 [29.25 30.52 34.3  ... 31.44 32.62 28.83]], shape=(120, 120), dtype=float16)
Calculating... 3
tf.Te

 [316.2 319.  319.2 ... 317.5 311.  304.2]], shape=(1220, 1220), dtype=float16)
Calculating... 113
tf.Tensor(
[[307.  300.  302.5 ... 310.5 308.  294.5]
 [311.  308.8 304.  ... 315.  307.  304. ]
 [297.2 296.5 293.2 ... 295.8 294.  292. ]
 ...
 [304.5 304.5 306.5 ... 311.8 307.5 306. ]
 [309.5 307.5 301.8 ... 310.8 310.  308. ]
 [305.5 304.8 300.5 ... 309.2 304.5 302.5]], shape=(1230, 1230), dtype=float16)
Calculating... 114
tf.Tensor(
[[316.8 316.8 306.2 ... 307.5 310.2 315. ]
 [302.8 296.2 288.8 ... 288.5 293.  304.2]
 [300.8 302.5 293.5 ... 299.  297.2 307.5]
 ...
 [315.8 315.8 304.5 ... 313.5 305.8 320.5]
 [315.  320.8 308.8 ... 317.  317.2 327. ]
 [307.8 314.5 299.  ... 305.  305.5 309.2]], shape=(1240, 1240), dtype=float16)
Calculating... 115
tf.Tensor(
[[318.8 317.5 318.5 ... 315.2 321.  319.5]
 [307.  305.  310.5 ... 302.8 307.5 300. ]
 [319.  306.8 311.  ... 311.5 319.  305. ]
 ...
 [320.5 324.5 322.2 ... 327.2 325.5 318. ]
 [319.2 312.2 318.2 ... 317.  314.  313.5]
 [308.5 30

 [422.5 429.5 422.  ... 408.8 417.  412. ]], shape=(1690, 1690), dtype=float16)
Calculating... 160
tf.Tensor(
[[423.2 421.  425.5 ... 424.2 417.  431.5]
 [430.2 423.8 426.5 ... 428.  422.2 430.2]
 [433.8 435.8 433.2 ... 437.  425.5 440.8]
 ...
 [422.8 428.2 425.8 ... 425.5 419.8 433.2]
 [428.5 432.5 431.5 ... 428.  420.2 437.5]
 [428.8 430.5 438.2 ... 428.2 425.8 443.2]], shape=(1700, 1700), dtype=float16)
Calculating... 161
tf.Tensor(
[[428.8 438.5 430.5 ... 426.8 429.  418.5]
 [412.5 416.8 406.5 ... 406.8 416.8 405.8]
 [426.2 425.8 427.  ... 420.5 430.8 415.8]
 ...
 [426.8 434.  426.2 ... 420.5 431.  407.8]
 [435.5 434.2 429.2 ... 423.2 437.2 417.8]
 [434.2 426.2 430.2 ... 427.2 433.2 418. ]], shape=(1710, 1710), dtype=float16)
Calculating... 162
tf.Tensor(
[[419.8 415.5 419.8 ... 419.5 425.2 428.2]
 [433.8 431.2 436.5 ... 431.8 443.5 438. ]
 [429.8 412.8 430.8 ... 426.2 431.  428.8]
 ...
 [420.8 415.5 424.8 ... 408.2 426.8 424.5]
 [412.2 412.  410.5 ... 407.  422.8 417.5]
 [424.  43

 [516.5 496.  499.8 ... 499.8 490.5 500.8]], shape=(2020, 2020), dtype=float16)
Calculating... 193
tf.Tensor(
[[505.  494.2 497.5 ... 500.2 500.  508.5]
 [499.8 492.5 494.  ... 497.  494.2 500.2]
 [499.5 483.5 494.2 ... 493.8 489.8 503. ]
 ...
 [493.5 489.  487.  ... 486.5 488.5 495. ]
 [502.5 488.  488.8 ... 493.5 487.2 498.5]
 [487.8 487.5 490.5 ... 487.5 492.5 505.8]], shape=(2030, 2030), dtype=float16)
Calculating... 194
tf.Tensor(
[[518.  512.5 515.5 ... 511.  507.2 518.5]
 [502.5 515.  506.2 ... 488.8 495.8 511. ]
 [501.  508.  521.  ... 490.2 497.5 517.5]
 ...
 [509.  508.  510.8 ... 494.8 492.8 514.5]
 [507.5 503.5 506.2 ... 503.5 494.2 508.2]
 [514.  515.  521.5 ... 499.8 501.  522. ]], shape=(2040, 2040), dtype=float16)
Calculating... 195
tf.Tensor(
[[506.  516.5 510.  ... 511.8 508.2 503.2]
 [495.5 506.5 496.5 ... 493.8 495.2 497. ]
 [503.2 511.5 505.2 ... 498.2 500.5 497.5]
 ...
 [515.  527.  508.8 ... 512.  515.  505.8]
 [497.2 507.5 486.  ... 500.2 504.2 491.8]
 [504.8 51

 [562.  558.  552.5 ... 562.  566.  558.5]], shape=(2270, 2270), dtype=float16)
Calculating... 218
tf.Tensor(
[[539.5 561.  563.5 ... 561.5 561.5 554.5]
 [547.5 562.5 573.5 ... 567.5 567.  561. ]
 [555.5 556.5 571.5 ... 575.  570.  563.5]
 ...
 [567.5 579.5 581.5 ... 583.  579.  571.5]
 [565.5 575.5 580.  ... 581.  581.  565. ]
 [568.5 584.  601.  ... 583.  588.5 574. ]], shape=(2280, 2280), dtype=float16)
Calculating... 219
tf.Tensor(
[[570.5 571.5 570.5 ... 590.5 562.  582.5]
 [564.5 562.  557.5 ... 584.5 561.  566. ]
 [561.5 564.  572.5 ... 585.5 557.5 571. ]
 ...
 [565.5 565.  565.  ... 583.5 557.  568. ]
 [572.  569.5 572.  ... 591.5 563.5 577.5]
 [562.  560.  550.  ... 584.  556.5 568. ]], shape=(2290, 2290), dtype=float16)
Calculating... 220
tf.Tensor(
[[578.  585.5 584.  ... 590.5 585.5 567.5]
 [569.5 581.5 583.  ... 580.  572.  564.5]
 [574.  576.  573.  ... 577.  570.  568. ]
 ...
 [583.  571.5 576.  ... 572.  578.  567.5]
 [564.  572.  573.5 ... 569.  570.5 552.5]
 [553.5 55

 [651.  654.5 642.5 ... 656.5 646.5 649. ]], shape=(2620, 2620), dtype=float16)
Calculating... 253
tf.Tensor(
[[643.5 651.5 657.5 ... 650.  646.  632. ]
 [651.  661.5 649.  ... 652.  657.  645.5]
 [625.5 647.  644.  ... 633.5 645.5 624.5]
 ...
 [654.  657.5 651.  ... 658.5 660.5 646.5]
 [665.  664.5 657.  ... 655.5 663.  646. ]
 [643.5 653.  652.  ... 650.  655.5 633.5]], shape=(2630, 2630), dtype=float16)
Calculating... 254
tf.Tensor(
[[678.  668.5 659.  ... 640.5 669.5 665.5]
 [649.5 654.  638.5 ... 631.5 644.5 650.5]
 [669.  677.  664.  ... 651.5 669.  674. ]
 ...
 [667.5 658.5 640.5 ... 637.5 644.  660. ]
 [658.  658.  642.  ... 636.5 652.  646.5]
 [662.5 665.  661.5 ... 652.5 663.5 665.5]], shape=(2640, 2640), dtype=float16)
Calculating... 255
tf.Tensor(
[[654.  659.  646.5 ... 652.5 656.  647.5]
 [668.  671.  661.  ... 664.  667.5 654.5]
 [666.  664.5 649.5 ... 658.  654.5 655. ]
 ...
 [663.5 665.5 656.  ... 659.  656.5 658.5]
 [649.5 663.5 643.  ... 659.  651.  652. ]
 [657.  66

 [718.5 721.  730.5 ... 714.  722.  729. ]], shape=(2890, 2890), dtype=float16)
Calculating... 280
tf.Tensor(
[[730.5 727.  707.5 ... 734.5 719.5 737. ]
 [747.  751.5 722.  ... 753.  734.5 741. ]
 [732.  730.5 712.5 ... 742.5 724.5 736.5]
 ...
 [731.  736.  704.5 ... 740.5 725.5 734.5]
 [726.  714.5 701.  ... 742.5 710.5 722. ]
 [721.5 717.5 701.5 ... 731.  714.  724.5]], shape=(2900, 2900), dtype=float16)
Calculating... 281
tf.Tensor(
[[722.5 732.  716.5 ... 733.  714.5 735. ]
 [723.5 732.5 712.  ... 723.5 711.  727.5]
 [721.5 726.5 721.5 ... 734.  722.5 731. ]
 ...
 [732.  744.  730.5 ... 742.  730.5 738.5]
 [726.  733.  728.5 ... 736.  733.  731.5]
 [719.5 729.5 714.  ... 732.  725.5 730. ]], shape=(2910, 2910), dtype=float16)
Calculating... 282
tf.Tensor(
[[749.  736.  744.  ... 725.  746.5 727. ]
 [739.  733.5 745.5 ... 734.  738.5 716.5]
 [738.5 715.5 723.5 ... 708.5 729.5 707. ]
 ...
 [733.5 725.5 742.5 ... 717.5 739.5 728. ]
 [731.  719.5 730.  ... 717.  724.  722.5]
 [719.5 69

 [785.5 798.  784.5 ... 799.5 776.5 782. ]], shape=(3190, 3190), dtype=float16)
Calculating... 310
tf.Tensor(
[[799.5 811.  793.5 ... 811.  788.  790.5]
 [781.  801.  796.  ... 807.  793.5 794.5]
 [787.5 788.  794.  ... 812.5 783.  786. ]
 ...
 [785.5 798.  799.5 ... 806.5 800.5 796. ]
 [804.5 821.  811.5 ... 819.5 807.5 815. ]
 [783.  799.5 794.5 ... 795.5 783.5 784. ]], shape=(3200, 3200), dtype=float16)
Calculating... 311
tf.Tensor(
[[818.  809.  826.5 ... 804.  806.  811. ]
 [798.5 801.5 810.  ... 785.  777.5 786. ]
 [813.  798.5 808.5 ... 788.  789.5 795.5]
 ...
 [813.5 804.5 822.  ... 789.  787.5 803. ]
 [803.  792.5 820.5 ... 782.  782.5 790. ]
 [811.5 796.5 811.  ... 775.5 787.  801. ]], shape=(3210, 3210), dtype=float16)
Calculating... 312
tf.Tensor(
[[803.5 821.  801.  ... 804.5 818.5 823.5]
 [795.  816.  785.5 ... 799.5 800.5 805. ]
 [790.5 814.  798.5 ... 796.5 796.5 813. ]
 ...
 [785.  805.5 786.  ... 788.  797.  799.5]
 [806.5 821.  802.  ... 810.5 805.  821. ]
 [791.  81

 [894.  884.5 872.5 ... 874.  876.  886.5]], shape=(3470, 3470), dtype=float16)
Calculating... 338
tf.Tensor(
[[859.5 875.  867.5 ... 853.  864.  834. ]
 [868.  875.  860.5 ... 845.  861.  840.5]
 [875.5 878.5 875.  ... 852.5 862.5 858.5]
 ...
 [867.5 872.5 872.5 ... 853.  872.5 851.5]
 [871.  889.  878.  ... 870.  864.5 862. ]
 [852.  860.5 861.  ... 840.5 852.5 835. ]], shape=(3480, 3480), dtype=float16)
Calculating... 339
tf.Tensor(
[[865.5 848.  869.  ... 880.5 855.5 872. ]
 [883.5 870.  886.5 ... 892.5 873.5 887.5]
 [878.  863.5 883.5 ... 894.  864.  875.5]
 ...
 [860.  845.  866.  ... 863.5 853.  863.5]
 [857.5 848.  871.  ... 871.5 846.5 868.5]
 [873.  855.  875.5 ... 882.5 863.5 872. ]], shape=(3490, 3490), dtype=float16)
Calculating... 340
tf.Tensor(
[[876.  854.5 847.5 ... 873.  863.  868. ]
 [882.5 869.  858.  ... 870.  856.5 866. ]
 [890.5 873.5 874.  ... 886.  875.  878.5]
 ...
 [898.  880.5 880.5 ... 888.5 878.5 886.5]
 [893.  876.5 876.5 ... 890.  878.5 899.5]
 [888.  87

 [938.  924.  953.  ... 920.5 934.5 951. ]], shape=(3770, 3770), dtype=float16)
Calculating... 368
tf.Tensor(
[[960.  953.5 941.5 ... 953.  944.  946. ]
 [931.  931.  923.  ... 933.5 930.  922. ]
 [952.5 936.5 931.5 ... 941.  939.5 939.5]
 ...
 [955.5 944.5 948.  ... 959.  950.5 954.5]
 [938.  928.  930.5 ... 936.  924.5 935. ]
 [934.5 929.  925.5 ... 940.5 927.  928. ]], shape=(3780, 3780), dtype=float16)
Calculating... 369
tf.Tensor(
[[962.  971.  955.  ... 953.5 936.  970.5]
 [949.5 968.5 950.  ... 943.5 931.  965.5]
 [959.5 950.5 942.5 ... 938.  918.5 958.5]
 ...
 [961.5 975.  962.  ... 958.  936.5 978. ]
 [951.5 958.5 949.5 ... 941.5 926.5 961.5]
 [934.  939.5 918.5 ... 913.  909.  941.5]], shape=(3790, 3790), dtype=float16)
Calculating... 370
tf.Tensor(
[[961.5 963.  941.5 ... 952.  967.5 953. ]
 [936.  953.  921.  ... 927.5 958.5 945. ]
 [964.5 958.5 953.5 ... 960.  970.5 962.5]
 ...
 [964.  960.  953.  ... 946.  975.5 960. ]
 [936.5 936.5 925.  ... 925.  949.  946.5]
 [947.5 94

 [1021.5 1016.  1011.  ... 1018.5 1004.  1007.5]], shape=(4040, 4040), dtype=float16)
Calculating... 395
tf.Tensor(
[[1008.   994.5 1014.  ...  991.5 1007.  1005. ]
 [ 996.   992.  1008.5 ... 1013.5 1015.5 1015.5]
 [1003.  1004.5 1008.5 ... 1005.5 1010.5 1017. ]
 ...
 [1008.   995.  1012.5 ... 1014.  1022.  1013.5]
 [ 991.   985.   995.  ...  985.  1007.   984.5]
 [1017.  1015.  1020.  ... 1010.  1017.  1022. ]], shape=(4050, 4050), dtype=float16)
Calculating... 396
tf.Tensor(
[[1023.  1016.5 1026.  ... 1003.  1001.5  999. ]
 [1040.  1034.  1028.  ... 1014.5 1029.  1014.5]
 [1033.  1018.5 1022.  ... 1005.  1014.   999. ]
 ...
 [1027.  1020.  1022.5 ... 1000.  1007.  1000. ]
 [1018.5 1004.  1014.5 ... 1006.  1011.   985. ]
 [1029.  1017.5 1021.  ... 1007.  1007.5  995. ]], shape=(4060, 4060), dtype=float16)
Calculating... 397
tf.Tensor(
[[1001.5 1000.  1005.  ... 1014.5 1001.5 1022.5]
 [1031.  1026.  1025.  ... 1022.  1010.5 1032. ]
 [1008.5 1005.   987.5 ... 1013.  1001.  1018. ]
 ...


tf.Tensor(
[[1064. 1089. 1079. ... 1080. 1092. 1103.]
 [1071. 1100. 1098. ... 1116. 1104. 1098.]
 [1070. 1089. 1093. ... 1099. 1098. 1094.]
 ...
 [1086. 1103. 1099. ... 1105. 1100. 1107.]
 [1056. 1081. 1071. ... 1075. 1077. 1073.]
 [1060. 1088. 1077. ... 1079. 1090. 1083.]], shape=(4340, 4340), dtype=float16)
Calculating... 425
tf.Tensor(
[[1085. 1105. 1097. ... 1095. 1086. 1098.]
 [1075. 1093. 1094. ... 1083. 1071. 1077.]
 [1064. 1102. 1100. ... 1084. 1089. 1088.]
 ...
 [1072. 1089. 1086. ... 1083. 1088. 1077.]
 [1080. 1099. 1095. ... 1097. 1085. 1090.]
 [1076. 1101. 1081. ... 1079. 1070. 1072.]], shape=(4350, 4350), dtype=float16)
Calculating... 426
tf.Tensor(
[[1079. 1082. 1100. ... 1073. 1092. 1094.]
 [1086. 1089. 1079. ... 1073. 1087. 1087.]
 [1060. 1066. 1068. ... 1058. 1070. 1074.]
 ...
 [1090. 1093. 1090. ... 1070. 1090. 1096.]
 [1081. 1080. 1085. ... 1078. 1089. 1085.]
 [1080. 1075. 1090. ... 1059. 1086. 1089.]], shape=(4360, 4360), dtype=float16)
Calculating... 427
tf.Tensor(

tf.Tensor(
[[1148. 1127. 1132. ... 1150. 1134. 1154.]
 [1155. 1142. 1147. ... 1163. 1153. 1162.]
 [1141. 1139. 1126. ... 1150. 1142. 1146.]
 ...
 [1142. 1138. 1133. ... 1160. 1148. 1163.]
 [1154. 1145. 1146. ... 1171. 1153. 1170.]
 [1159. 1156. 1152. ... 1168. 1154. 1184.]], shape=(4590, 4590), dtype=float16)
Calculating... 450
tf.Tensor(
[[1163. 1144. 1167. ... 1159. 1157. 1161.]
 [1127. 1120. 1147. ... 1156. 1132. 1142.]
 [1155. 1126. 1147. ... 1154. 1141. 1147.]
 ...
 [1130. 1118. 1125. ... 1137. 1124. 1118.]
 [1147. 1131. 1135. ... 1148. 1136. 1147.]
 [1145. 1119. 1149. ... 1155. 1136. 1144.]], shape=(4600, 4600), dtype=float16)
Calculating... 451
tf.Tensor(
[[1135. 1145. 1127. ... 1139. 1139. 1166.]
 [1152. 1170. 1139. ... 1159. 1151. 1166.]
 [1154. 1170. 1161. ... 1171. 1147. 1177.]
 ...
 [1149. 1175. 1157. ... 1156. 1147. 1171.]
 [1148. 1160. 1147. ... 1154. 1150. 1158.]
 [1129. 1152. 1140. ... 1140. 1126. 1150.]], shape=(4610, 4610), dtype=float16)
Calculating... 452
tf.Tensor(

tf.Tensor(
[[1207. 1202. 1195. ... 1226. 1213. 1225.]
 [1208. 1206. 1198. ... 1209. 1215. 1203.]
 [1216. 1216. 1209. ... 1214. 1212. 1224.]
 ...
 [1196. 1197. 1194. ... 1206. 1197. 1200.]
 [1203. 1186. 1203. ... 1205. 1213. 1202.]
 [1225. 1221. 1226. ... 1225. 1212. 1218.]], shape=(4850, 4850), dtype=float16)
Calculating... 476
tf.Tensor(
[[1219. 1216. 1214. ... 1224. 1214. 1210.]
 [1225. 1207. 1225. ... 1222. 1214. 1214.]
 [1222. 1208. 1227. ... 1227. 1224. 1222.]
 ...
 [1233. 1226. 1243. ... 1227. 1227. 1229.]
 [1214. 1200. 1205. ... 1218. 1213. 1206.]
 [1199. 1196. 1199. ... 1188. 1182. 1183.]], shape=(4860, 4860), dtype=float16)
Calculating... 477
tf.Tensor(
[[1229. 1215. 1240. ... 1221. 1224. 1224.]
 [1214. 1199. 1237. ... 1216. 1216. 1205.]
 [1216. 1194. 1238. ... 1207. 1211. 1198.]
 ...
 [1222. 1217. 1228. ... 1219. 1226. 1218.]
 [1210. 1193. 1210. ... 1206. 1199. 1213.]
 [1213. 1206. 1238. ... 1214. 1213. 1217.]], shape=(4870, 4870), dtype=float16)
Calculating... 478
tf.Tensor(

tf.Tensor(
[[1278. 1285. 1291. ... 1281. 1291. 1285.]
 [1259. 1280. 1277. ... 1267. 1271. 1262.]
 [1269. 1278. 1275. ... 1270. 1282. 1263.]
 ...
 [1254. 1258. 1267. ... 1253. 1278. 1252.]
 [1257. 1270. 1274. ... 1267. 1278. 1260.]
 [1253. 1272. 1263. ... 1266. 1268. 1249.]], shape=(5130, 5130), dtype=float16)
Calculating... 504
tf.Tensor(
[[1260. 1271. 1251. ... 1270. 1248. 1250.]
 [1274. 1272. 1268. ... 1276. 1274. 1272.]
 [1285. 1278. 1265. ... 1284. 1269. 1274.]
 ...
 [1295. 1299. 1295. ... 1290. 1278. 1299.]
 [1299. 1296. 1293. ... 1297. 1280. 1296.]
 [1279. 1278. 1269. ... 1284. 1278. 1286.]], shape=(5140, 5140), dtype=float16)
Calculating... 505
tf.Tensor(
[[1275. 1294. 1309. ... 1282. 1292. 1280.]
 [1261. 1278. 1279. ... 1265. 1280. 1262.]
 [1275. 1284. 1277. ... 1282. 1283. 1274.]
 ...
 [1268. 1290. 1296. ... 1265. 1279. 1270.]
 [1281. 1291. 1301. ... 1301. 1300. 1284.]
 [1271. 1287. 1307. ... 1291. 1299. 1292.]], shape=(5150, 5150), dtype=float16)
Calculating... 506
tf.Tensor(

tf.Tensor(
[[1342. 1360. 1354. ... 1350. 1357. 1356.]
 [1356. 1372. 1354. ... 1364. 1364. 1368.]
 [1329. 1340. 1337. ... 1357. 1346. 1355.]
 ...
 [1350. 1357. 1345. ... 1367. 1357. 1356.]
 [1342. 1363. 1350. ... 1363. 1348. 1363.]
 [1351. 1351. 1348. ... 1357. 1364. 1364.]], shape=(5390, 5390), dtype=float16)
Calculating... 530
tf.Tensor(
[[1356. 1366. 1369. ... 1344. 1365. 1356.]
 [1359. 1365. 1365. ... 1350. 1371. 1348.]
 [1366. 1370. 1368. ... 1348. 1366. 1347.]
 ...
 [1367. 1366. 1357. ... 1329. 1366. 1337.]
 [1342. 1348. 1351. ... 1315. 1355. 1319.]
 [1355. 1348. 1339. ... 1323. 1352. 1334.]], shape=(5400, 5400), dtype=float16)
Calculating... 531
tf.Tensor(
[[1351. 1335. 1325. ... 1338. 1342. 1328.]
 [1346. 1329. 1336. ... 1345. 1344. 1351.]
 [1340. 1321. 1311. ... 1326. 1335. 1334.]
 ...
 [1348. 1338. 1341. ... 1342. 1356. 1352.]
 [1344. 1319. 1308. ... 1324. 1335. 1338.]
 [1371. 1351. 1341. ... 1361. 1358. 1353.]], shape=(5410, 5410), dtype=float16)
Calculating... 532
tf.Tensor(

tf.Tensor(
[[1405. 1427. 1421. ... 1430. 1392. 1401.]
 [1408. 1420. 1395. ... 1415. 1375. 1388.]
 [1410. 1419. 1418. ... 1428. 1386. 1396.]
 ...
 [1420. 1438. 1413. ... 1444. 1403. 1416.]
 [1419. 1424. 1410. ... 1449. 1397. 1411.]
 [1411. 1424. 1422. ... 1418. 1383. 1409.]], shape=(5660, 5660), dtype=float16)
Calculating... 557
tf.Tensor(
[[1436. 1421. 1427. ... 1429. 1413. 1417.]
 [1428. 1418. 1414. ... 1425. 1413. 1404.]
 [1423. 1410. 1410. ... 1423. 1420. 1406.]
 ...
 [1400. 1407. 1382. ... 1408. 1393. 1376.]
 [1399. 1407. 1408. ... 1425. 1402. 1391.]
 [1419. 1413. 1404. ... 1418. 1401. 1398.]], shape=(5670, 5670), dtype=float16)
Calculating... 558
tf.Tensor(
[[1417. 1419. 1387. ... 1404. 1414. 1436.]
 [1406. 1421. 1403. ... 1425. 1445. 1431.]
 [1385. 1402. 1378. ... 1401. 1419. 1423.]
 ...
 [1389. 1405. 1379. ... 1396. 1412. 1409.]
 [1411. 1416. 1384. ... 1415. 1423. 1423.]
 [1421. 1418. 1385. ... 1422. 1426. 1422.]], shape=(5680, 5680), dtype=float16)
Calculating... 559
tf.Tensor(

tf.Tensor(
[[1473. 1471. 1480. ... 1485. 1489. 1488.]
 [1469. 1478. 1481. ... 1507. 1505. 1487.]
 [1478. 1491. 1482. ... 1503. 1510. 1487.]
 ...
 [1466. 1461. 1471. ... 1484. 1482. 1472.]
 [1472. 1484. 1476. ... 1504. 1503. 1503.]
 [1471. 1484. 1481. ... 1501. 1494. 1487.]], shape=(5930, 5930), dtype=float16)
Calculating... 584
tf.Tensor(
[[1458. 1428. 1423. ... 1434. 1430. 1458.]
 [1480. 1461. 1467. ... 1474. 1468. 1491.]
 [1475. 1465. 1466. ... 1460. 1454. 1476.]
 ...
 [1478. 1462. 1466. ... 1469. 1454. 1478.]
 [1491. 1476. 1477. ... 1492. 1471. 1491.]
 [1500. 1484. 1475. ... 1485. 1470. 1501.]], shape=(5940, 5940), dtype=float16)
Calculating... 585
tf.Tensor(
[[1480. 1469. 1466. ... 1463. 1482. 1478.]
 [1460. 1460. 1475. ... 1465. 1469. 1464.]
 [1480. 1467. 1464. ... 1474. 1474. 1490.]
 ...
 [1467. 1467. 1472. ... 1473. 1472. 1490.]
 [1478. 1483. 1482. ... 1464. 1486. 1486.]
 [1466. 1471. 1477. ... 1468. 1484. 1491.]], shape=(5950, 5950), dtype=float16)
Calculating... 586
tf.Tensor(

Calculating... 15
tf.Tensor(
[[62.5  65.7  61.   ... 62.97 60.44 64.44]
 [62.8  63.53 62.78 ... 60.5  59.66 61.6 ]
 [64.7  64.94 62.8  ... 62.6  60.8  65.  ]
 ...
 [63.2  62.53 65.   ... 60.6  61.8  63.72]
 [63.88 66.5  65.25 ... 61.9  63.72 65.25]
 [62.84 65.9  66.56 ... 62.72 62.38 64.1 ]], shape=(250, 250), dtype=float16)
Calculating... 16
tf.Tensor(
[[66.44 63.22 61.2  ... 65.25 61.28 66.94]
 [71.   67.75 62.7  ... 68.44 62.5  68.8 ]
 [69.75 65.75 62.78 ... 65.3  61.38 67.1 ]
 ...
 [68.06 64.7  58.28 ... 67.25 57.   63.3 ]
 [66.1  61.22 58.06 ... 64.9  56.56 62.6 ]
 [68.44 70.06 63.97 ... 70.94 64.75 70.8 ]], shape=(260, 260), dtype=float16)
Calculating... 17
tf.Tensor(
[[69.06 72.06 72.8  ... 73.25 72.4  67.94]
 [65.75 69.   66.1  ... 66.9  67.4  66.3 ]
 [65.94 67.9  69.2  ... 67.7  70.6  64.25]
 ...
 [64.1  69.8  65.4  ... 67.44 68.25 67.06]
 [62.62 68.5  66.94 ... 66.9  67.94 64.94]
 [60.3  62.5  62.72 ... 63.94 60.84 58.9 ]], shape=(270, 270), dtype=float16)
Calculating... 18
t

 [113.   118.75 114.7  ... 116.4  115.56 119.56]], shape=(480, 480), dtype=float16)
Calculating... 39
tf.Tensor(
[[126.9  120.5  122.25 ... 120.4  119.4  122.9 ]
 [123.6  121.25 119.25 ... 118.9  119.1  121.4 ]
 [126.4  123.8  120.5  ... 125.4  117.1  124.25]
 ...
 [120.6  113.75 112.25 ... 116.6  111.56 115.25]
 [120.06 116.6  113.1  ... 119.   113.1  114.5 ]
 [120.2  113.56 114.4  ... 117.7  111.5  114.75]], shape=(490, 490), dtype=float16)
Calculating... 40
tf.Tensor(
[[123.25 127.   122.75 ... 124.5  129.   131.2 ]
 [126.25 130.2  125.44 ... 124.94 129.6  132.8 ]
 [122.3  124.06 119.9  ... 119.4  125.5  123.9 ]
 ...
 [129.2  133.9  122.44 ... 128.4  134.5  130.5 ]
 [121.25 122.56 115.94 ... 122.44 122.1  122.6 ]
 [121.8  122.6  119.4  ... 118.5  128.   122.9 ]], shape=(500, 500), dtype=float16)
Calculating... 41
tf.Tensor(
[[130.   129.   123.25 ... 126.6  124.   122.  ]
 [132.5  128.6  126.9  ... 122.5  126.6  120.9 ]
 [127.94 125.3  124.5  ... 124.9  118.9  119.56]
 ...
 [127.25 

tf.Tensor(
[[184.1 183.2 190.5 ... 186.9 191.1 180.2]
 [185.5 191.  196.4 ... 188.8 202.5 188. ]
 [180.9 187.1 189.1 ... 185.5 197.5 183. ]
 ...
 [179.5 182.8 189.9 ... 186.2 191.8 184.5]
 [186.6 186.4 189.2 ... 182.9 194.6 183.5]
 [182.9 184.5 185.8 ... 181.8 189.8 180. ]], shape=(740, 740), dtype=float16)
Calculating... 65
tf.Tensor(
[[178.9 187.1 186.1 ... 195.6 180.5 188.9]
 [187.5 196.1 192.9 ... 200.  193.  197.9]
 [184.9 186.  189.5 ... 195.1 189.8 190.5]
 ...
 [175.2 182.1 183.  ... 189.8 179.1 184.8]
 [186.2 193.8 188.9 ... 193.2 187.4 193.2]
 [172.4 179.6 180.2 ... 187.8 172.5 185.1]], shape=(750, 750), dtype=float16)
Calculating... 66
tf.Tensor(
[[186.4 188.9 187.1 ... 195.5 185.6 189. ]
 [184.  180.5 176.8 ... 188.4 180.  179.8]
 [193.  191.4 188.6 ... 199.1 193.5 194.4]
 ...
 [195.1 189.1 187.  ... 201.1 194.8 192. ]
 [186.8 192.1 187.2 ... 198.5 189.6 187. ]
 [185.1 180.5 181.1 ... 191.6 184.6 182.5]], shape=(760, 760), dtype=float16)
Calculating... 67
tf.Tensor(
[[185.6 